version: '3.1'

services: 
  drupal:
    image: drupal
    ports: 
    - "8080:80"
    volumes: 
    - drupal-modules:/var/www/html/modules
    - drupal-profiles:/var/www/html/profiles
    - drupal-themes:/var/www/html/themes
    - drupal-sites:/var/www/html/sites

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - psql-data:/var/lib/postgresql/data
    ports: 
    - "5432:5432"

volumes:
  psql-data:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites: