version: '3.1'

services: 
  drupal:
    image: drupal:8.2
    ports: 
    - "8080:80"
    volumes: 
    - drupal-modules:/var/www/html/modules
    - drupal-profiles:/var/www/html/profiles
    - drupal-themes:/var/www/html/themes
    - drupal-sites:/var/www/html/sites

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD_FILE: /run/secrets/psql_pass3
    secrets:
      - psql_pass3
    volumes:
      - drupal-data:/var/lib/postgresql/data
    ports: 
    - "5432:5432"
secrets:
  psql_pass3:
    external: true
volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites: